app:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/product_opinion
    username: root
    password: 'zaq1@WSX'
    pool-size: 30

server:
  error:
    include-message: 'always'